# Text Prediction 
## Description
### This task is related to Natural Language Processing. Create a Deep Learning model such that the modal should predict the next occurring word when given a sentence.

In [ ]:
## Installing required libraries

In [6]:
pip install keras

In [9]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [15]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from  tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding

In [3]:
data =""" One morning, when Gregor Samsa woke from troubled dreams, he found
himself transformed in his bed into a horrible vermin.  He lay on
his armour-like back, and if he lifted his head a little he could
see his brown belly, slightly domed and divided by arches into stiff
sections.  The bedding was hardly able to cover it and seemed ready
to slide off any moment.  His many legs, pitifully thin compared
with the size of the rest of him, waved about helplessly as he
looked."""

In [52]:
# Integer encode text
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data=tokenizer.texts_to_sequences([data])[0]
encoded_data[:10]

[9, 10, 11, 12, 13, 14, 15, 16, 17, 1]

In [5]:
# describe vocab size
vocab_size=len(tokenizer.word_index)+1
vocab_size

71

In [8]:
sequences=list()
for i in range(1,len(encoded_data)):
    sequence=encoded_data[i-1:i+1]
    sequences.append(sequence)
len(sequences)
    

85

In [53]:
sequences[:10]

array([[ 9, 10],
       [10, 11],
       [11, 12],
       [12, 13],
       [13, 14],
       [14, 15],
       [15, 16],
       [16, 17],
       [17,  1],
       [ 1, 18]])

In [54]:
sequences=array(sequences)
x,y=sequences[:,0],sequences[:,1]

In [55]:
x[:5]

array([ 9, 10, 11, 12, 13])

In [56]:
y[:5]

array([10, 11, 12, 13, 14])

In [57]:
# Converts a class vector(integers)to binary class matrix
y=to_categorical(y,num_classes=vocab_size)
y[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0

In [ ]:
# Creating a Sequential Model 

In [59]:
model=Sequential()
# Embeding layer
model.add(Embedding(vocab_size,10,input_length=1))
# Recurrent layer
model.add(LSTM(50))
# Fully connected layer
model.add(Dense(vocab_size,activation='relu'))
# Output Layer
model.add(Dense(vocab_size,activation='softmax'))
print(model.summary())


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 1, 10)             710       
                                                                 
 lstm_8 (LSTM)               (None, 50)                12200     
                                                                 
 dense_10 (Dense)            (None, 71)                3621      
                                                                 
 dense_11 (Dense)            (None, 71)                5112      
                                                                 
Total params: 21,643
Trainable params: 21,643
Non-trainable params: 0
_________________________________________________________________
None


In [60]:
# Compiling the model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [61]:
model.fit(x,y,epochs=100)

Epoch 1/100
3/3 [==============================] - 4s 7ms/step - loss: 4.2630 - accuracy: 0.0118
Epoch 2/100
3/3 [==============================] - 0s 8ms/step - loss: 4.2607 - accuracy: 0.0706
Epoch 3/100
3/3 [==============================] - 0s 8ms/step - loss: 4.2590 - accuracy: 0.0941
Epoch 4/100
3/3 [==============================] - 0s 8ms/step - loss: 4.2572 - accuracy: 0.0824
Epoch 5/100
3/3 [==============================] - 0s 7ms/step - loss: 4.2553 - accuracy: 0.0706
Epoch 6/100
3/3 [==============================] - 0s 9ms/step - loss: 4.2534 - accuracy: 0.0706
Epoch 7/100
3/3 [==============================] - 0s 9ms/step - loss: 4.2514 - accuracy: 0.0824
Epoch 8/100
3/3 [==============================] - 0s 7ms/step - loss: 4.2490 - accuracy: 0.0824
Epoch 9/100
3/3 [==============================] - 0s 8ms/step - loss: 4.2465 - accuracy: 0.0824
Epoch 10/100
3/3 [==============================] - 0s 8ms/step - loss: 4.2441 - accuracy: 0.0824
Epoch 11/100
3/3 [===========