In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
b=[1,2,3,4,5,6]
print(b)

[1, 2, 3, 4, 5, 6]


In [3]:
print(a.dtype)

int32


In [5]:
c=np.array([[10,20,30],[40,50,60]])
print(c)

[[10 20 30]
 [40 50 60]]


In [6]:
d=np.array([[20,30,40],[50,60,70]])
print(d)

[[20 30 40]
 [50 60 70]]


In [7]:
print(c+d)

[[ 30  50  70]
 [ 90 110 130]]


In [12]:
f=np.ones((3,3),dtype=int)
print(f)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
g=np.full((2,4),3)
print(g)

[[3 3 3 3]
 [3 3 3 3]]


In [13]:
zero_arr=np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
ones=np.ones(50)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [15]:
ones_int=np.ones(5,dtype=int)
print(ones_int)

[1 1 1 1 1]


In [17]:
ones_arr=np.ones((4,4),dtype=int)
print(ones_arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
